sudo: required
dist: trusty
os:
        - linux
        - osx
compiler:
        - clang
        - gcc
language: c

before_install:
        - export LD_LIBRARY_PATH=`pwd`/samples/:$LD_LIBRARY_PATH
        - sudo ./ci/install_deps.sh

script:
        - ./make.sh test
